###
## binary_sensor/internet.yaml
###

- platform: template
  sensors:
    internet_state:
      entity_id:
        - sensor.internet_link
        - sensor.internet_ago
      value_template: >
        {% if states.sensor.internet_ago.state|int > 30 %}False{% else %}True{% endif %}
    internet_slow:
      entity_id:
        - sensor.internet_receive
        - sensor.internet_receive_statistics
        - input_number.internet_deviation
      value_template: >-
        {% if states.sensor.internet_receive_statistics is defined and states.sensor.internet_receive_statistics.attributes.standard_deviation|float > 0.0 %}
        {{ (((states.sensor.internet_receive_mean.state|float) - (states.sensor.internet_receive.state|float))
             / (states.sensor.internet_receive_statistics.attributes.standard_deviation|float) 
           > (states.input_number.internet_deviation.state|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad
    internet_fast:
      entity_id:
        - sensor.internet_receive
        - sensor.internet_receive_statistics
        - input_number.internet_deviation
      value_template: >-
        {% if states.sensor.internet_receive_statistics is defined and states.sensor.internet_receive_statistics.attributes.standard_deviation|float > 0 %}
        {{ (((states.sensor.internet_receive.state|float) - (states.sensor.internet_receive_mean.state|float))
             / (states.sensor.internet_receive_statistics.attributes.standard_deviation|float)) 
           > (states.input_number.internet_deviation.state|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy
    internet_slow_persistent:
      entity_id:
        - sensor.internet_receive
        - sensor.internet_receive_stdev_mean
        - input_number.internet_deviation
      value_template: >-
        {% if states.sensor.internet_receive_stdev_mean is defined and states.sensor.internet_receive_stdev_mean.state|float > 0 %}
        {{ (((states.sensor.internet_receive_mean.state|float) - (states.sensor.internet_receive.state|float))
             / (states.sensor.internet_receive_stdev_mean.state|float) 
           > (states.input_number.internet_deviation.state|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad
    internet_fast_persistent:
      entity_id:
        - sensor.internet_receive
        - sensor.internet_receive_stdev_mean
        - input_number.internet_deviation
      value_template: >-
        {% if states.sensor.internet_receive_stdev_mean is defined and states.sensor.internet_receive_stdev_mean.state|float > 0 %} 
        {{ (((states.sensor.internet_receive.state|float) - (states.sensor.internet_receive_mean.state|float))
             / (states.sensor.internet_receive_stdev_mean.state|float)) 
           > (states.input_number.internet_deviation.state|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy

