###
## binary_sensor/intranet.yaml
###

- platform: template
  sensors:
    intranet_state:
      entity_id:
        - sensor.intranet_link
        - sensor.intranet_ago
      value_template: >
        {% if states.sensor.intranet_ago.state|int > 30 %}False{% else %}True{% endif %}
    intranet_slow:
      entity_id:
        - sensor.intranet_receive
        - sensor.intranet_receive_statistics
        - input_number.intranet_deviation
      value_template: >-
        {% if states.sensor.intranet_receive_statistics is defined and states.sensor.intranet_receive_statistics.attributes.standard_deviation|float > 0 %}
        {{ (((states.sensor.intranet_receive_mean.state|float) - (states.sensor.intranet_receive.state|float))
             / (states.sensor.intranet_receive_statistics.attributes.standard_deviation|float) 
           > (states.input_number.intranet_deviation.state|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad
    intranet_fast:
      entity_id:
        - sensor.intranet_receive
        - sensor.intranet_receive_statistics
        - input_number.intranet_deviation
      value_template: >-
        {% if states.sensor.intranet_receive_statistics is defined and states.sensor.intranet_receive_statistics.attributes.standard_deviation|float > 0 %}
        {{ (((states.sensor.intranet_receive.state|float) - (states.sensor.intranet_receive_mean.state|float))
             / (states.sensor.intranet_receive_statistics.attributes.standard_deviation|float)) 
           > (states.input_number.intranet_deviation.state|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy
    intranet_slow_persistent:
      entity_id:
        - sensor.intranet_receive
        - sensor.intranet_receive_stdev_mean
        - input_number.intranet_deviation
      value_template: >-
        {% if states.sensor.intranet_receive_stdev_mean is defined and states.sensor.intranet_receive_stdev_mean.state|float > 0 %}
        {{ (((states.sensor.intranet_receive_mean.state|float) - (states.sensor.intranet_receive.state|float))
             / (states.sensor.intranet_receive_stdev_mean.state|float) 
           > (states.input_number.intranet_deviation.state|float)) }}
        {% else %}null{% endif %}
      icon_template: >
          mdi:emoticon-sad
    intranet_fast_persistent:
      entity_id:
        - sensor.intranet_receive
        - sensor.intranet_receive_stdev_mean
        - input_number.intranet_deviation
      value_template: >-
        {% if states.sensor.intranet_receive_stdev_mean is defined and states.sensor.intranet_receive_stdev_mean.state|float > 0 %}
        {{ (((states.sensor.intranet_receive.state|float) - (states.sensor.intranet_receive_mean.state|float))
             / (states.sensor.intranet_receive_stdev_mean.state|float)) 
           > (states.input_number.intranet_deviation.state|float) }}
        {% else %}null{% endif %}
      icon_template: >-
          mdi:emoticon-happy
