###
# configuration.yaml
###

# DEFAULT
default_config:

# HTTP
http:
  base_url: !secret ha-url
  server_port: !secret ha-port

# TTS
tts:
  - platform: google_translate

# FAVICON
favicon:
  title: !secret ha-name
  icon_path: /local/favicons/

# PYTHON
python_script:

# LOGGER
logger:
  default: !secret logger-default

# MQTT
mqtt:
  broker: !secret mqtt-broker
  port: !secret mqtt-port
  username: !secret mqtt-username
  password: !secret mqtt-password

###
### RECORDER, HISTORY, LOGBOOK components
###

history: !include history.yaml
#recorder: !include recorder.yaml
#logbook: !include logbook.yaml

###
### PRIMARY components
###

#input_boolean: !include input_booleans.yaml
#input_text: !include input_texts.yaml

## history_graphs
history_graph: !include_dir_merge_named history_graph
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number

## groups
group: !include_dir_merge_named group

## automations
automation: !include_dir_merge_list automation

## counters
counter: !include_dir_merge_named counter

## WEBLINKS
#weblink: !include weblinks.yaml

camera camera_all: !include_dir_merge_list camera
sensor sensor_all: !include_dir_merge_list sensor
binary_sensor binary_sensor_all: !include_dir_merge_list binary_sensor
#device_tracker motion: !include_dir_merge_list device_tracker

###
### TIME_DATE
###

sensor datetime:
  - platform: time_date
    display_options:
      - date
      - time

###
### PANEL
###

panel_iframe:
  netdata:
    title: NetData
    icon: mdi:speedometer
    url: !secret netdata-url

###
### HOST
###

sensor host_wan_ip:
  - platform: rest
    name: host_wan_ip
    resource: http://ip.jsontest.com
    value_template: >
      {%- if value_json is defined -%}
        {{ value_json.ip | default(null) }}
      {%- else -%}null{%- endif -%}

sensor host_lan_ip:
  - platform: command_line
    command: echo '{"date":'$(date "+%s")',"hostname":"'$(hostname)'","ipv4":"'$(ip addr | egrep "global" | sed "s/.* \([0-9\.]*\)\/.*/\1/" | head -1)'"}'
    name: host_lan_ip
    scan_interval: 14400
    command_timeout: 30
    json_attributes:
      - date
      - hostname
      - ipv4
    value_template: >
      {%- if value_json is defined -%}
        {{ value_json.ipv4 }}
      {%- else -%}null{%- endif -%}

sensor host_uname:
  - platform: command_line
    name: host_uname
    command: echo '{"date":'$(date "+%s")',"hardware":"'$(uname -m)'","nodename":"'$(uname -n)'","processor":"'$(uname -p)'","os_release":"'$(uname -r)'","os_name":"'$(uname -s)'","os_version":"'$(uname -v)'"}'
    scan_interval: 14400
    command_timeout: 30
    json_attributes:
      - date
      - hardware
      - nodename
      - os_release
      - os_name
      - os_version
    value_template: >
      {%- if value_json is defined -%}
        {{ value_json.date | int | timestamp_custom("%a %b %d @ %I:%M %p") }}
      {%- else -%}null{%- endif -%}
