###
## camera/annotated.yaml
###

- platform: mqtt
  name: motion_event_annotated
  topic: '+/+/+/image/end/+'

- platform: generic
  name: motion_annotated_picture
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_annotated_picture') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_testsignal_picture') }}{% endif %}
