###
## camera/detected_entity.yaml
###

- platform: generic
  name: motion_detected_entity_picture
  verify_ssl: false
  limit_refetch_to_url_change: true
  still_image_url: >-
    {% set p = states('sensor.motion_detected_entity_picture') %}
    {% if p != 'unknown' and p != 'null' and p|length > 0 %}
      {{ p }}
    {% else %}{{ states('sensor.motion_nosignal_picture') }}{% endif %}
