###
## sensor/motion.yaml
###

- platform: template
  sensors:
    motion_base_url:
      entity_id:
        - input_number.homeassistant_port
        - input_select.homeassistant_url
      value_template: >-
        {% if states.input_select.homeassistant_url.state|string == 'local' %}
          {{ 'http://' + states.sensor.host_lan_ip.attributes.ipv4 + ':' + states.input_number.homeassistant_port.state|int|string }}
        {% elif states.input_select.homeassistant_url.state|string == 'remote' %}
          {{ states.input_text.homeassistant_url.state }}
        {% else %}null{% endif %}

## annotations that detected entity(s)
- platform: template
  sensors:
    motion_groups:
      value_template: >
        {{ ('family','cars','utility','neighbors','friends')|list }}
    motion_family:
      value_template: >
        {{ ('david','keli','hali','ian','riley','ellen')|list }}
    motion_cars:
      value_template: >
        {{ ('mini','c70','c30','xc90','sprinter','suburban','rtv1100','tractor')|list }}
    motion_utility:
      value_template: >
        {{ ('ups','usps','fedex','amazon','propane','pge','att','comcast','poolboy')|list }}
    motion_neighhors:
      value_template: >
        {{ ('fletcher','soukoulis','wcox','ccox')|list }}
    motion_friends:
      value_template: >
        {{ ('miriam','corrine')|list }}
