###
## sensor/intranet.yaml
###

- platform: command_line
  command: iperf3 -c 192.168.1.40 -J | jq '{"date":.start.timestamp.timesecs,"send":.end.sum_sent.bits_per_second,"receive":.end.sum_received.bits_per_second}'
  name: intranet_link
  scan_interval: 300
  command_timeout: 60
  json_attributes:
    - date
    - send
    - receive
  value_template: >
    {%- if value_json is defined -%}
      {{ value_json.date | timestamp_custom("%a %b %d @ %I:%M %p") }}
    {%- else -%}null{%- endif -%}
- platform: template
  sensors:
    intranet_link_receive:
      entity_id:
        - sensor.intranet_link
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_link.attributes.receive is defined and states.sensor.intranet_link.attributes.receive != null %}
          {{ '%0.2f' | format(states.sensor.intranet_link.attributes.receive / 1000000.0) }}
        {%- else -%}null{%- endif -%}
    intranet_link_send:
      entity_id:
        - sensor.intranet_link
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_link.attributes.send is defined and states.sensor.intranet_link.attributes.send != null %}
          {{ '%0.2f' | format(states.sensor.intranet_link.attributes.send / 1000000.0) }}
        {%- else -%}null{%- endif -%}
    intranet_receive_mean:
      entity_id:
        - sensor.intranet_receive_statistics
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_receive_statistics is defined %}
          {{ states.sensor.intranet_receive_statistics.state }}
        {%- else -%}null{%- endif -%}
    intranet_receive_min_value:
      entity_id:
        - sensor.intranet_receive_statistics
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_receive_statistics is defined %}
          {{ states.sensor.intranet_receive_statistics.attributes.min_value }}
        {%- else -%}null{%- endif -%}
    intranet_receive_max_value:
      entity_id:
        - sensor.intranet_receive_statistics
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_receive_statistics is defined %}
          {{ states.sensor.intranet_receive_statistics.attributes.max_value }}
        {%- else -%}null{%- endif -%}
    intranet_receive_standard_deviation:
      entity_id:
        - sensor.intranet_receive_statistics
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_receive_statistics is defined %}
          {{ states.sensor.intranet_receive_statistics.attributes.standard_deviation }}
        {%- else -%}null{%- endif -%}
    intranet_send_mean:
      entity_id:
        - sensor.intranet_send_statistics
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_send_statistics is defined %}
          {{ states.sensor.intranet_send_statistics.state }}
        {%- else -%}null{%- endif -%}
    intranet_send_min_value:
      entity_id:
        - sensor.intranet_send_statistics
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_send_statistics is defined %}
          {{ states.sensor.intranet_send_statistics.attributes.min_value }}
        {%- else -%}null{%- endif -%}
    intranet_send_max_value:
      entity_id:
        - sensor.intranet_send_statistics
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_send_statistics is defined %}
          {{ states.sensor.intranet_send_statistics.attributes.max_value }}
        {%- else -%}null{%- endif -%}
    intranet_send_standard_deviation:
      entity_id:
        - sensor.intranet_send_statistics
      unit_of_measurement: Mbps
      value_template: >
        {% if states.sensor.intranet_send_statistics is defined %}
          {{ states.sensor.intranet_send_statistics.attributes.standard_deviation }}
        {%- else -%}null{%- endif -%}
    intranet_link_ago:
      entity_id:
        - sensor.intranet_link
        - sun.sun
      unit_of_measurement: seconds
      value_template: '{{ (now().timestamp()|int) - (states.sensor.intranet_link.attributes.date|int) }}'
    intranet_link_state:
      entity_id:
        - sensor.intranet_link_ago
      value_template: >
        {% if states.sensor.intranet_link_ago.state|int > 30 %}False{% else %}True{% endif %}
    intranet_count:
      entity_id:
        - sensor.intranet_link_count
      unit_of_measurement: tests
      value_template: >
        {% if states.sensor.intranet_link_count is defined %}
          {{ states.sensor.intranet_link_count.state }}
        {%- else -%}null{%- endif -%}
- platform: statistics
  entity_id: sensor.intranet_link_send
  name: intranet_send_statistics
  max_age:
    hours: 24
- platform: statistics
  entity_id: sensor.intranet_link_receive
  name: intranet_receive_statistics
  max_age:
    hours: 24
- platform: history_stats
  name: intranet_link_count
  entity_id: sensor.intranet_link_state
  state: True
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'
